<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3047" started-at="2020-02-11T06:28:37Z" finished-at="2020-02-11T06:28:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3047" started-at="2020-02-11T06:28:37Z" finished-at="2020-02-11T06:28:40Z">
      <class name="com.powderhook.appium.cases.homescreen.VerifyCheckinBack">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.powderhook.appium.cases.homescreen.VerifyCheckinBack@5c072e3f]" name="setUp" is-config="true" duration-ms="2852" started-at="2020-02-11T06:28:37Z" finished-at="2020-02-11T06:28:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="nameBefore(java.lang.reflect.Method)[pri:0, instance:com.powderhook.appium.cases.homescreen.VerifyCheckinBack@5c072e3f]" name="nameBefore" is-config="true" duration-ms="6" started-at="2020-02-11T06:28:40Z" finished-at="2020-02-11T06:28:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public static void com.powderhook.appium.cases.homescreen.VerifyCheckinBack.verifyCheckInBack()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nameBefore -->
        <test-method status="PASS" signature="verifyCheckInBack()[pri:0, instance:com.powderhook.appium.cases.homescreen.VerifyCheckinBack@5c072e3f]" name="verifyCheckInBack" duration-ms="10" started-at="2020-02-11T06:28:40Z" finished-at="2020-02-11T06:28:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCheckInBack -->
        <test-method status="FAIL" signature="tearDown(org.testng.ITestContext)[pri:0, instance:com.powderhook.appium.cases.homescreen.VerifyCheckinBack@5c072e3f]" name="tearDown" is-config="true" duration-ms="94" started-at="2020-02-11T06:28:40Z" finished-at="2020-02-11T06:28:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@35dab4eb]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.powderhook.appium.base.Base.tearDown(Base.java:79)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.powderhook.appium.cases.homescreen.VerifyCheckinBack -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
